apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata: 
  name: portafolio-backendconfig
  namespace: portfolio-app
spec:
  securityPolicy:
    name: "cloud-armor-portfolio-dev"
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 5
    healhtyThreshold: 2
    unhealhtyThreshold: 2
    type: HTTP
    requestPath: /health
    port: 8080
