apiVersion: v1
kind: ServiceAccount
metadata:
  name: portafolio-sa
  namespace: portfolio-app
  annotations: 
    iam.gke.io/gcp-service-account: "vertex-ai-sa-dev@portfolio-dev-local.iam.gserviceaccount.com"